<script src="./dist/plugins/jquery.min.js"></script>
<script src="./dist/plugins/modernizr.custom.js"></script>
<script src="./dist/plugins/bootstrap/bootstrap.min.js"></script>
<script src="./dist/plugins/bootstrap-offcanvas/bootstrap.offcanvas.min.js"></script>
<!-- <script src="./dist/plugins/typeahead/typeahead.bundle.min.js"></script> -->
<script src="./dist/plugins/typeahead/jquery.typeahead.custom.min.js"></script>
<script src="./dist/plugins/chosen/chosen.jquery.js"></script>
<script src="./dist/plugins/jquery.flexslider-min.js"></script>
<script src="./dist/plugins/jquery.zoom.min.js"></script>
<script src="./dist/plugins/flexmenu/flexmenu.js"></script>
<script src="./dist/plugins/main.js"></script>